#!/usr/bin/env bash

set -e

EXEC_NAME=train-box
SRC="target/aarch64-unknown-linux-gnu/debug/${EXEC_NAME}"
DST="/home/hlefevre/${EXEC_NAME}"

scp "${SRC}" "pifive:${DST}"
#ssh pifive "chmod +x ${DST} && ${DST}"
